const { DIAN_CONFIG } = require('./src/config/dianConfig');

console.log("--- DIAGNOSTICO DE CONFIGURACION DIAN ---");
console.log("AMBIENTE DETECTADO:", DIAN_CONFIG.AMBIENTE === '1' ? 'PRODUCCION 🚀' : 'HABILITACION/PRUEBAS 🧪');
console.log("NIT EMISOR:", DIAN_CONFIG.EMISOR.NIT);
console.log("RAZON SOCIAL:", DIAN_CONFIG.EMISOR.RAZON_SOCIAL);
console.log("SOFTWARE ID:", DIAN_CONFIG.SOFTWARE.ID ? DIAN_CONFIG.SOFTWARE.ID.substring(0, 5) + '...' : 'NO DEFINIDO');
console.log("TEST SET ID:", DIAN_CONFIG.SOFTWARE.TEST_SET_ID);
console.log("RESOLUCION PREFIJO:", DIAN_CONFIG.RESOLUCION.PREFIJO);
console.log("RESOLUCION RANGO:", DIAN_CONFIG.RESOLUCION.RANGO_DESDE, "al", DIAN_CONFIG.RESOLUCION.RANGO_HASTA);
console.log("URL ENDPOINT:", DIAN_CONFIG.AMBIENTE === '1' ? DIAN_CONFIG.ENDPOINTS.PRODUCCION.URL : DIAN_CONFIG.ENDPOINTS.HABILITACION.URL);
console.log("-----------------------------------------");
